name = "FigureGeneration"
uuid = "b201116c-8639-42fa-8ada-85b4ad167d25"
authors = ["Daisuke <nakada0907@outlook.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
